#!/usr/bin/env python3
"""Writes src/tvcharset.inc: the tables of the single-byte character sets of TvCharset (byte -> Unicode), from the codecs of Python.
usage: python3 tools/gen-charsets.py > src/tvcharset.inc
The ids are the numbers of the code pages of Windows where there is one (437, 866, 1251 ...); KOI8-R 20866, KOI8-U 21866, ISO-8859-n 28590 + n,
Mac Roman 10000. A byte that the set does not define comes out as $FFFF (the ASCII half is always the identity)."""
import codecs

SETS = []
for n in (437, 720, 737, 775, 850, 852, 855, 857, 858, 860, 861, 862, 863, 864, 865, 866, 869, 874):
    SETS.append((n, 'cp%d' % n, ['cp%d' % n, 'ibm%d' % n, '%d' % n]))
SETS.append((1125, 'cp1125', ['cp1125', 'ibm1125', 'cp866u', '1125']))
for n in range(1250, 1259):
    SETS.append((n, 'cp%d' % n, ['windows-%d' % n, 'cp%d' % n, '%d' % n]))
SETS.append((20866, 'koi8_r', ['koi8-r', 'koi8r']))
SETS.append((21866, 'koi8_u', ['koi8-u', 'koi8u']))
for n in (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16):
    SETS.append((28590 + n, 'iso8859_%d' % n, ['iso-8859-%d' % n, 'latin%d' % n if n in (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16) and False else 'iso8859-%d' % n]))
SETS.append((10000, 'mac_roman', ['macintosh', 'mac-roman', 'macroman']))

out = []
out.append('{ Generated by tools/gen-charsets.py - do not edit. The tables of the single-byte character sets of TvCharset: byte -> Unicode ($FFFF: undefined). }')
used = []
for ident, codec, names in SETS:
    try:
        codecs.lookup(codec)
    except LookupError:
        continue
    table = []
    for b in range(256):
        if b < 128:
            table.append(b)
            continue
        try:
            ch = bytes([b]).decode(codec)
            cp = ord(ch[0]) if len(ch) == 1 else 0xFFFF
        except UnicodeDecodeError:
            cp = 0xFFFF
        table.append(cp)
    used.append((ident, names))
    out.append('')
    out.append('const Charset%d: array[0..255] of Word = (' % ident)
    for i in range(0, 256, 16):
        out.append('  ' + ', '.join('$%04X' % v for v in table[i:i + 16]) + (',' if i < 240 else ''))
    out.append(');')
out.append('')
out.append('const')
out.append('  CharsetCount = %d;' % len(used))
out.append('  CharsetIds: array[0..%d] of LongInt = (%s);' % (len(used) - 1, ', '.join(str(i) for i, _ in used)))
out.append('  CharsetTables: array[0..%d] of Pointer = (%s);' % (len(used) - 1, ', '.join('@Charset%d' % i for i, _ in used)))
names = []
for ident, ns in used:
    for n in ns:
        names.append((n.lower(), ident))
out.append('  CharsetNameCount = %d;' % len(names))
out.append('  CharsetNames: array[0..%d] of record N: string[16]; Id: LongInt end = (' % (len(names) - 1))
for i, (n, ident) in enumerate(names):
    out.append("    (N: '%s'; Id: %d)%s" % (n, ident, ',' if i < len(names) - 1 else ''))
out.append('  );')
print('\n'.join(out))
