#!/usr/bin/env python3
"""Generates src/tvwidth.inc: ranges of zero-width and double-width code points,
from the Unicode Character Database that ships with Python (unicodedata).

  zero width : categories Mn, Me, Cf (except U+00AD), and Hangul Jamo medial
               vowels and final consonants U+1160..U+11FF
  double     : East Asian Width W or F
Control characters (C0, DEL, C1) are not in the tables; TvUtf8.CharWidth returns -1
for them. Run: python3 tools/gen-width.py > src/tvwidth.inc
"""
import sys, unicodedata

def ranges(pred):
    out, start, prev = [], None, None
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            ok = False
        else:
            ok = pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1)); start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out

def zero(cp):
    if cp == 0xAD:
        return False
    if 0x1160 <= cp <= 0x11FF:
        return True
    return unicodedata.category(chr(cp)) in ('Mn', 'Me', 'Cf')

def wide(cp):
    return unicodedata.east_asian_width(chr(cp)) in ('W', 'F')

def emit(name, rs):
    print("const")
    print("  %sCount = %d;" % (name, len(rs)))
    print("  %s: array[0..%sCount - 1] of TUnicodeRange = (" % (name, name))
    lines = []
    for i, (a, b) in enumerate(rs):
        lines.append("    (Lo: $%X; Hi: $%X)" % (a, b))
    print(",\n".join(lines))
    print("  );")
    print()

print("{ Generated by tools/gen-width.py from Unicode %s (Python unicodedata). Do not edit. }" % unicodedata.unidata_version)
print()
emit("ZeroWidthRanges", ranges(zero))
emit("WideRanges", ranges(wide))
