#!/usr/bin/env python3
"""Generates src/tvcp.inc: tables byte -> Unicode code point for DOS code pages,
as they are displayed on screen: the control characters 0..31 and 7Fh are shown as
the IBM PC graphic symbols (the 'glyph' view of the character ROM), the upper half
comes from the Python codec of the page.

usage: python3 tools/gen-codepage.py > src/tvcp.inc
"""
import sys

# the OEM code pages of DOS that Python knows (what DOS reports by INT 21h AX=6601h)
IDS = [437, 737, 775, 850, 852, 855, 857, 858, 860, 861, 862, 863, 864, 865, 866, 869, 1125]   # 1125: the DOS page of Ukrainian (RUSCII)
PAGES = [("Cp%d" % i, "cp%d" % i) for i in IDS]

# Unicode code points of the IBM PC glyphs for bytes 00h..1Fh and 7Fh
LOW = [0x0000, 0x263A, 0x263B, 0x2665, 0x2666, 0x2663, 0x2660, 0x2022,
       0x25D8, 0x25CB, 0x25D9, 0x2642, 0x2640, 0x266A, 0x266B, 0x263C,
       0x25BA, 0x25C4, 0x2195, 0x203C, 0x00B6, 0x00A7, 0x25AC, 0x21A8,
       0x2191, 0x2193, 0x2192, 0x2190, 0x221F, 0x2194, 0x25B2, 0x25BC]
DEL = 0x2302

def table(codec):
    t = []
    for b in range(256):
        if b < 0x20:
            t.append(LOW[b])
        elif b == 0x7F:
            t.append(DEL)
        elif b < 0x80:
            t.append(b)
        else:
            try:
                c = bytes([b]).decode(codec)
            except UnicodeDecodeError:
                c = "\ufffd"          # undefined in the page
            assert len(c) == 1 and ord(c) <= 0xFFFF
            t.append(ord(c))
    return t

print("{ Generated by tools/gen-codepage.py (Python codecs, IBM PC glyphs for the low half). Do not edit. }")
print()
print("const")
for name, codec in PAGES:
    t = table(codec)
    print("  %s: array[0..255] of Word = (" % name)
    for i in range(0, 256, 8):
        print("    " + ", ".join("$%04X" % v for v in t[i:i + 8]) + ("," if i < 248 else ""))
    print("  );")
    print()
