{ TvCodePg: translation between a single-byte DOS code page and Unicode.

  Translated from magiblot/tvision @ b4831e2:
    source/platform/codepage.cpp (CpTranslator)
  The tables are generated by tools/gen-codepage.py (see tvcp.inc). Borland
  disclaimer and MIT notice: COPYRIGHT.magiblot.

  Bytes that are not valid UTF-8 are shown through the current code page. The
  control characters 0..31 and 7Fh are shown as the IBM PC graphic symbols. The
  default page is 866 (tv/DESIGN.md, rule 5); magiblot's default is 437. }
unit TvCodePg;

{$I tvdefs.inc}

interface

const
  cpIdCp437 = 437;
  cpIdCp866 = 866;
  cpIdCp1125 = 1125;
  { the OEM pages of DOS that are known: 437 737 775 850 852 855 857 858 860 861 862 863 864
    865 866 869 1125 (tools/gen-codepage.py; 1125 is the page of Ukrainian); the page that DOS has chosen by the locale of the
    host (INT 21h AX=6601h) is used by TvDos }

{ Selects the current code page; False if the page is not known. }
function CpSelect(Id: Integer): Boolean;
function CpCurrent: Integer;

{ Code point displayed for byte B in the current page. }
function CpToUnicode(B: Byte): LongWord;
{ Byte for a code point, or 0 if the page has no such character. }
function CpFromUnicode(CodePoint: LongWord): Byte;
{ UTF-8 of CpToUnicode(B) written to Buf (4 bytes at least); returns its length. }
function CpToUtf8(B: Byte; Buf: PByte): Integer;
{ The plain ASCII sign that stands for a character that the page lacks (the DOS screen has one page): a line of a frame is - = | + , a block is # : % ., an arrow
  < > ^ v, a bullet *, a typographic quote or dash its ASCII form; 0 if there is none (then ?). }
function CpFallback(CodePoint: LongWord): Byte;

implementation

uses
  TvUtf8;

{$I tvcp.inc}

type
  PCpTable = ^TCpTable;
  TCpTable = array[0..255] of Word;

var
  Current: Integer = cpIdCp866;
  Table: PCpTable = @Cp866;
  { reverse map, sorted by code point: Rev[I] = code point, RevByte[I] = byte }
  Rev: array[0..255] of LongWord;
  RevByte: array[0..255] of Byte;

procedure BuildReverse;
var
  I, J: Integer;
  CP: LongWord;
  B: Byte;
begin
  for I := 0 to 255 do
  begin
    Rev[I] := Table^[I];
    RevByte[I] := I;
  end;
  { insertion sort; for equal code points the lowest byte comes first }
  for I := 1 to 255 do
  begin
    CP := Rev[I];
    B := RevByte[I];
    J := I - 1;
    while (J >= 0) and (Rev[J] > CP) do
    begin
      Rev[J + 1] := Rev[J];
      RevByte[J + 1] := RevByte[J];
      Dec(J);
    end;
    Rev[J + 1] := CP;
    RevByte[J + 1] := B;
  end;
end;

function CpSelect(Id: Integer): Boolean;
begin
  Result := True;
  case Id of
    437: Table := @Cp437;
    737: Table := @Cp737;
    775: Table := @Cp775;
    850: Table := @Cp850;
    852: Table := @Cp852;
    855: Table := @Cp855;
    857: Table := @Cp857;
    858: Table := @Cp858;
    860: Table := @Cp860;
    861: Table := @Cp861;
    862: Table := @Cp862;
    863: Table := @Cp863;
    864: Table := @Cp864;
    865: Table := @Cp865;
    866: Table := @Cp866;
    869: Table := @Cp869;
    1125: Table := @Cp1125;
  else
    Exit(False);
  end;
  Current := Id;
  BuildReverse;
end;

function CpCurrent: Integer;
begin
  Result := Current;
end;

function CpFallback(CodePoint: LongWord): Byte;
begin
  Result := 0;
  case CodePoint of
    $2500, $2501, $2504, $2505, $2508, $2509, $254C, $254D, $2574, $2576, $257C, $257E:
      Result := Ord('-');
    $2550:
      Result := Ord('=');
    $2502, $2503, $2506, $2507, $250A, $250B, $254E, $254F, $2551, $2575, $2577, $257D, $257F:
      Result := Ord('|');
    $2580..$2587:
      Result := Ord('-');
    $2588:
      Result := Ord('#');
    $2589..$2590:
      Result := Ord('|');
    $2591:
      Result := Ord('.');
    $2592:
      Result := Ord(':');
    $2593:
      Result := Ord('%');
    $2190, $25C4:
      Result := Ord('<');
    $2192, $25BA:
      Result := Ord('>');
    $2191, $25B2:
      Result := Ord('^');
    $2193, $25BC:
      Result := Ord('v');
    $2022, $2219, $25CF:
      Result := Ord('*');
    $2018, $2019:
      Result := 39;                { the apostrophe }
    $201C, $201D:
      Result := 34;                { the double quote }
    $2013, $2014:
      Result := Ord('-');
    $00A0:
      Result := Ord(' ');
  else
    if (CodePoint >= $2500) and (CodePoint <= $257F) then
      Result := Ord('+');          { corners, crosses and tees of any weight }
  end;
end;

function CpToUnicode(B: Byte): LongWord;
begin
  Result := Table^[B];
end;

function CpFromUnicode(CodePoint: LongWord): Byte;
var
  Lo, Hi, Mid: Integer;
begin
  Lo := 0;
  Hi := 255;
  while Lo < Hi do
  begin
    Mid := (Lo + Hi) shr 1;
    if Rev[Mid] < CodePoint then
      Lo := Mid + 1
    else
      Hi := Mid;
  end;
  if Rev[Lo] = CodePoint then
    Result := RevByte[Lo]
  else
    Result := 0;
end;

function CpToUtf8(B: Byte; Buf: PByte): Integer;
begin
  Result := Utf8Encode(Table^[B], Buf);
end;

initialization
  BuildReverse;
end.
